// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4oC6C6ekhcbAiXvV7H3VjvLwrroNJUmc',
    appId: '1:694875987197:web:ad841970d4a5112c8d7294',
    messagingSenderId: '694875987197',
    projectId: 'finance-e6c23',
    authDomain: 'finance-e6c23.firebaseapp.com',
    storageBucket: 'finance-e6c23.appspot.com',
    measurementId: 'G-Z6TJR4X4CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1i_k_r30aEkvcroeGaBIJ4CyNgteR5Q',
    appId: '1:694875987197:android:4bf67600ed9f15998d7294',
    messagingSenderId: '694875987197',
    projectId: 'finance-e6c23',
    storageBucket: 'finance-e6c23.appspot.com',
  );
}
